# **Đại số tuyến tính (Linear Algebra)**

**Đại số** là một nhánh của Toán học (bên cạnh Hình học, Giải tích, và Xác suất thống kê). 
- "Đại" có nghĩa là đại diện, và "số" là con số.
- Trong Đại số, dùng các chữ cái (x, y, z, A, B) để đại diện cho những con số chưa biết hoặc có thể thay đổi. 
    - VD: 
        + Tính toán số học tĩnh: $2 + 3 = 5$
        + Đại số: $2x + 3 = 7$. 

    => Xây dựng các công thức tổng quát và giải quyết các bài toán tìm ẩn số.

**Tuyến tính**:
- "Tuyến": đường thằng, "tính": tính chất. "Tuyến tính" là có tính chất của một đường thẳng.
- Một mối quan hệ được gọi là "tuyến tính" nếu nó thỏa mãn hai tính chất sau:
    - Tính tỷ lệ (Scaling): Đầu vào tăng/giảm bao nhiêu lần thì đầu ra tăng/giảm bấy nhiêu lần.
        - Ví dụ: 1 bát phở giá 40k. 2 bát phở giá 80k. 10 bát phở giá 400k. Mối quan hệ giữa số bát phở và số tiền là tuyến tính. Mọi thứ tăng lên theo một tỷ lệ cố định.
    - Tính cộng (Additivity): Tổng các thành phần gộp lại bằng chính tổng của từng thành phần tính riêng.
        - Ví dụ: Tiền mua 1 bát phở (40k) + tiền mua 1 cốc trà đá (5k) = 45k.

**Đại số tuyến tính (Linear Algebra)** là môn toán học dùng các chữ cái/biến số (Đại số) để nghiên cứu những hệ thống hoạt động theo tỷ lệ đường thẳng (Tuyến tính).
- Ví dụ có hệ phương trình: 
    $$\begin{cases} 2x + 3y = 6 \\ x - y = 1 \end{cases}$$
    
    Cả hai đều là phương trình đường thẳng (bậc 1). 
- Đại số tuyến tính: nghiên cứu cách giải những hệ phương trình bậc 1 nhiều ẩn.
- Về mặt hình học, mỗi phương trình là một đường thẳng. Giải hệ phương trình thực chất là đi tìm giao điểm duy nhất mà hai đường thẳng đó cắt nhau. Khi hệ phương trình có hàng nghìn ẩn số và hàng nghìn phương trình phối hợp với nhau, không thể nhìn thấy giao điểm trong không gian 1000 chiều được. => nén toàn bộ hệ phương trình đó thành một phương trình ma trận dạng:
    $$\mathbf{A}\mathbf{x} = \mathbf{b}$$

**Trường hợp: là hệ phương trình bậc 1 nhưng không tuyến tính?**
- Ví dụ có hệ phương trình sau:
    $$\begin{cases} z_1 = 2x + y + 3 \\ z_2 = x - y + 1 \end{cases}$$

- Tất cả các ẩn số $x, y$ đều là bậc 1.
- => Kiểm tra: hệ phương trình trên có thỏa mãn tính chất của một mối quan hệ tuyến tính?
    - Cho $x = 1, y = 1$: 
        - $z_1 = 2(1) + 1 + 3 = 6$
        - $z_2 = 1 - 1 + 1 = 1$

    input (1,1) => output (6,1)
    - Nhân đôi input: $2 \times (1,1)$ => $x = 2, y = 2$
        - $z_1 = 2(2) + 2 + 3 = 9$
        - $z_2 = 2 - 2 + 1 = 1$
    
    input (2,2) => output (9,1) 
    
    => vi phạm tính chất tuyến tính: nhân đôi input, thì buộc output cũng phải nhân đôi!

=> Hệ phương trình bậc 1 nhưng không tuyến tính được gọi là Hệ phương trình không thuần nhất. Thuật ngữ: Hệ Affine

**Hệ Tuyến tính vs Hệ Affine**:
Trong một hệ phương trình tổng quát: $\mathbf{A}\mathbf{x} = \mathbf{b}$
- Nếu $\mathbf{b} = \mathbf{0}$ (Hệ thuần nhất): Tất cả các phương trình trong hệ đều đi qua gốc tọa độ. Đây là hệ phương trình Tuyến tính thuần túy.
- Nếu $\mathbf{b} \neq \mathbf{0}$ (Hệ Affine): Các phương trình có hằng số tự do đứng độc lập, đồ thị bị dịch chuyển lệch khỏi gốc tọa độ.

Nhưng vẫn gọi chung việc giải hệ $\mathbf{A}\mathbf{x} = \mathbf{b}$ là Đại số tuyến tính vì dù hệ đó có bị lệch khỏi gốc tọa độ ($\mathbf{b} \neq \mathbf{0}$) hay không, thì thuật toán và công cụ ma trận để giải chúng là giống nhau.

Với ví dụ hệ Affine đã nêu trên:
    $$\begin{cases} 2x + y + 3 = z_1 \\ x - y + 1 = z_2 \end{cases}$$
Nó được viết dưới dạng ma trận như sau:
    $$\begin{bmatrix} 2 & 1 \\ 1 & -1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} + \begin{bmatrix} 3 \\ 1 \end{bmatrix} = \begin{bmatrix} z_1 \\ z_2 \end{bmatrix}$$
- Đây chính là dạng $\mathbf{A}\mathbf{x} + \mathbf{b} = \mathbf{z}$. 
- Vector độ lệch $\mathbf{b} = \begin{bmatrix} 3 \\ 1 \end{bmatrix}$: toàn bộ không gian nghiệm bị dịch chuyển lệch khỏi gốc tọa độ $(0,0)$


## **1. Cấu trúc Dữ liệu tuyến tính**

Trong học máy (machine learning), mọi dữ liệu (hình ảnh, âm thanh, văn bản,...) đều được số hóa và quản lý dựa trên "Số chiều không gian" (dimension).

Số chiều không gian có thể là 0, 1, 2 hoặc nhiều hơn (n). Thuật ngữ "tensor" được sử dụng để chỉ mảng có n chiều. (Thay vì nói n-dimensional array thì gọi là tensor).

**Tensor** là một thực thể hình học tổng quát hóa của số, Vector và ma trận lên mọi số chiều.
- Tensor bậc 0 (Rank-0 Tensor): Chính là Scalar (Số vô hướng), có 0 chiều.
- Tensor bậc 1 (Rank-1 Tensor): Chính là Vector (Vector), có 1 chiều.
- Tensor bậc 2 (Rank-2 Tensor): Chính là Matrix (Ma trận), có 2 chiều.
- Tensor bậc 3 (Rank-3 Tensor): Một khối ma trận 3 chiều (Ví dụ: Một bức ảnh màu RGB gồm chiều Rộng $\times$ Chiều Cao $\times$ 3 Kênh Màu).
- Tensor bậc $n$ (Rank-$n$ Tensor): Mảng dữ liệu chứa $n$ chiều tổng quát.

#### **1.1. Số vô hướng**
Số vô hướng (Scalar) chỉ là một con số cụ thể đơn lẻ. Về mặt hình học, nó đại diện cho một điểm không có kích thước, không có hướng trên một vạch số (Không gian 0 chiều).

Ví dụ: Thực hiện một bài kiểm tra toán được 9 điểm thì điểm số này là một số vô hướng.

In [1]:
import numpy as np

math = np.array(9)
phy = np.array(8)
chem = np.array(7)
print("Điểm trung bình 3 môn = ", (math+phy+chem)/3)

Điểm trung bình 3 môn =  8.0


In [2]:
math.ndim

0

#### **1.2. Vector**


#### **1.3. Ma trận**
Vector là đại lượng một chiều nên chỉ có thể biểu diễn thuộc tính cho một đối tượng duy nhất. Trong thực tế, chúng ta thường xuyên phải quản lý một tập hợp gồm nhiều đối tượng, mỗi đối tượng lại có nhiều đặc trưng. Để xếp chồng các vector này lại với nhau một cách ngăn nắp, chúng ta cần tới một cấu trúc 2 chiều là Ma trận (Matrix).

Ký hiệu toán học: Ma trận được ký hiệu bằng một chữ cái in đậm và viết hoa như $\mathbf{A}, \mathbf{B}, \mathbf{X}$. Ký hiệu $\mathbf{A} \in \mathbb{R}^{m \times n}$ nghĩa là ma trận số thực $\mathbf{A}$ có $m$ dòng và $n$ cột:
    $$\mathbf{A}=\begin{bmatrix} 
    a_{11} & a_{12} & \cdots & a_{1n} \\ 
    a_{21} & a_{22} & \cdots & a_{2n} \\ 
    \vdots & \vdots & \ddots & \vdots \\ 
    a_{m1} & a_{m2} & \cdots & a_{mn} \\ 
    \end{bmatrix}_{m \times n}$$

- Để định vị phần tử ở dòng $i$, cột $j$, ta ký hiệu là $\mathbf{A}_{ij}$ (hoặc $a_{ij}$).
- Vector dòng thứ $i$ được ký hiệu là $\mathbf{A}^{(i)}$.
- Vector cột thứ $j$ được ký hiệu là $\mathbf{A}_{j}$.

**Các ma trận đặc biệt**:
- Ma trận vuông (Square Matrix): Là ma trận có số dòng bằng số cột ($m=n$). 
- Ma trận đơn vị (Identity Matrix - Ký hiệu là $\mathbf{I}$): Là ma trận vuông có tất cả các phần tử trên đường chéo chính bằng $1$, còn lại bằng $0$. Ma trận đơn vị đóng vai trò tương tự như số 1 trong đại số thông thường: Bất kỳ ma trận nào nhân với ma trận đơn vị cũng bằng chính nó ($\mathbf{A}\mathbf{I} = \mathbf{A}$).
    $$\mathbf{I}_3 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$
- Ma trận đường chéo (Diagonal Matrix): Là ma trận vuông chỉ có các phần tử nằm trên đường chéo chính là khác 0, toàn bộ các vị trí khác đều bằng 0.
    $$\mathbf{A}_2 = \begin{bmatrix} -4 & 0 \\ 0 & 2 \end{bmatrix}$$
    $$\mathbf{B}_3 = \begin{bmatrix} 3 & 0 & 0 \\ 0 & -2 & 0 \\ 0 & 0 & 5 \end{bmatrix}$$
    $$\mathbf{C}_2 = \begin{bmatrix} -4 & 0 \\ 0 & 0 \end{bmatrix}$$
- Ma trận chuyển vị (Transpose Matrix - Ký hiệu là $\mathbf{A}^{\top}$): Là ma trận có được bằng cách biến dòng thành cột, biến cột thành dòng của ma trận gốc ($b_{ij} = a_{ji}$).
    $$\mathbf{A} = \begin{bmatrix} 1 & 2 & 3 \\ 3 & 2 & 1 \end{bmatrix} \implies \mathbf{A}^{\top} = \begin{bmatrix} 1 & 3 \\ 2 & 2 \\ 3 & 1 \end{bmatrix}$$

**Các phép toán trên ma trận**:

In [5]:
A = np.array([[1.0, 2.0, 3.0],
[3.0, 2.0, 1.0],
[4.0, 2.0, 2.0]])

B = np.array([[2.0, 1.0],
[1.0, 3.0],
[1.0, 1.0]])

print(A)
print()
print(B)

[[1. 2. 3.]
 [3. 2. 1.]
 [4. 2. 2.]]

[[2. 1.]
 [1. 3.]
 [1. 1.]]


In [6]:
A.shape

(3, 3)

In [7]:
B.shape

(3, 2)

##### **Phép toán 1: Phép cộng, trừ ma trận**
Quy tắc: Hai ma trận bắt buộc phải có cùng kích thước ($m \times n$). Lấy các phần tử ở cùng vị trí tương ứng để cộng hoặc trừ với nhau.

Ví dụ:
$$\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} + \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} = \begin{bmatrix} 1+5 & 2+6 \\ 3+7 & 4+8 \end{bmatrix} = \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}$$

In [ ]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [11]:
B = np.array([[5,6], [7,8]])
B

array([[5, 6],
       [7, 8]])

In [12]:
A + B

array([[ 6,  8],
       [10, 12]])

In [13]:
A - B

array([[-4, -4],
       [-4, -4]])

In [14]:
B - A

array([[4, 4],
       [4, 4]])

##### **Phép toán 2: Phép nhân ma trận thông thường (Matrix Multiplication)**
Quy tắc: Để nhân được $\mathbf{A} \times \mathbf{B}$, thì số cột của ma trận trước phải bằng số dòng của ma trận sau ($\mathbf{A}_{m \times n} \times \mathbf{B}_{n \times p} = \mathbf{C}_{m \times p}$). Phần tử $c_{ij}$ của ma trận kết quả được tính bằng cách lấy vector dòng $i$ của $\mathbf{A}$ nhân vô hướng (nhân từng cặp rồi cộng tổng) với vector cột $j$ của $\mathbf{B}$.

Ví dụ:
$$\mathbf{A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad \mathbf{B} = \begin{bmatrix} 2 & 0 \\ 1 & 5 \end{bmatrix}$$

$$\mathbf{A} \times \mathbf{B} = \begin{bmatrix} 4 & 10 \\ 10 & 20 \end{bmatrix}$$

Lấy Hàng nhân Cột:
- Dòng 1 nhân Cột 1: $(1 \times 2) + (2 \times 1) = 4$
- Dòng 1 nhân Cột 2: $(1 \times 0) + (2 \times 5) = 10$
- Dòng 2 nhân Cột 1: $(3 \times 2) + (4 \times 1) = 10$
- Dòng 2 nhân Cột 2: $(3 \times 0) + (4 \times 5) = 20$

Syntax: 
```bash 
C = A @ B
```

In [16]:
A = np.array([[1.0, 2.0, 3.0],
[3.0, 2.0, 1.0],
[4.0, 2.0, 2.0]])

A

array([[1., 2., 3.],
       [3., 2., 1.],
       [4., 2., 2.]])

In [17]:
B = np.array([[2.0, 1.0],
[1.0, 3.0],
[1.0, 1.0]])

B

array([[2., 1.],
       [1., 3.],
       [1., 1.]])

In [18]:
C = A @ B
C

array([[ 7., 10.],
       [ 9., 10.],
       [12., 12.]])

In [19]:
D = B @ A
D

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

Quy tắc thực hiện nhân thông thường 2 ma trận: Số cột của ma trận đứng trước phải bằng Số dòng của ma trận đứng sau:

$$\mathbf{A}_{(3 \times \underline{3})} \quad @ \quad \mathbf{B}_{(\underline{3} \times 2)}$$
- Điều kiện được thỏa mãn!
- Ma trận kết quả C sẽ lấy số dòng của A và số cột của B, tức là kích thước $3 \times 2$.

$$\mathbf{B}_{(3 \times \underline{2})} \quad @ \quad \mathbf{A}_{(\underline{3} \times 3)}$$
- Số cột của ma trận đứng trước (B) là 2.
- Số dòng của ma trận đứng sau (A) là 3.
- Vì $2 \neq 3$, máy tính không thể thực hiện thuật toán lấy "Vector hàng của B nhân vô hướng với Vector cột của A" được (hàng của B chỉ có 2 phần tử, trong khi cột của A có tới 3 phần tử, bị lệch nhau).

##### **Phép toán 3: Phép tích Hadamard (Element-wise Multiplication)**
Quy tắc: Hai ma trận phải cùng kích thước. Máy tính nhân trực tiếp các phần tử có cùng vị trí với nhau mà không có sự hòa trộn hàng-cột. 

Ký hiệu toán học: $\mathbf{A} \odot \mathbf{B}$.

Ví dụ:
$$\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \odot \begin{bmatrix} 2 & 0 \\ 1 & 5 \end{bmatrix} = \begin{bmatrix} 1\cdot2 & 2\cdot0 \\ 3\cdot1 & 4\cdot5 \end{bmatrix} = \begin{bmatrix} 2 & 0 \\ 3 & 20 \end{bmatrix}$$

In [20]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [21]:
B = np.array([[2,0], [1,5]])
B

array([[2, 0],
       [1, 5]])

In [22]:
A * B

array([[ 2,  0],
       [ 3, 20]])

In [23]:
B * A

array([[ 2,  0],
       [ 3, 20]])

##### **Phép toán 4: Phép tích vô hướng ma trận (Frobenius Inner Product)**
Quy tắc: Áp dụng cho hai ma trận có cùng kích thước. Ta lấy tích Hadamard của chúng (nhân từng vị trí tương ứng) rồi cộng tất cả các phần tử lại với nhau để thu được một con số duy nhất (số vô hướng). 

Ký hiệu: $\langle \mathbf{A}, \mathbf{B} \rangle_F$.

Ví dụ:
$$\mathbf{A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad \mathbf{B} = \begin{bmatrix} 2 & 0 \\ 1 & 5 \end{bmatrix}$$

$$\langle \mathbf{A}, \mathbf{B} \rangle_F = (1\cdot2) + (2\cdot0) + (3\cdot1) + (4\cdot5) = 2 + 0 + 3 + 20 = 25$$

In [24]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [25]:
B = np.array([[2,0], [1,5]])
B

array([[2, 0],
       [1, 5]])

In [26]:
np.sum(A*B)

25

##### **Phép toán 5: Nhân ma trận với số vô hướng (Scalar Multiplication)**
Quy tắc: Lấy một số thực hằng số $k$ nhân với ma trận $\mathbf{A}$. Ta chỉ việc nhân số $k$ đó vào từng phần tử bên trong ma trận.

Ví dụ: Với $k = 3$:
$$3 \times \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} = \begin{bmatrix} 3\cdot1 & 3\cdot2 \\ 3\cdot3 & 3\cdot4 \end{bmatrix} = \begin{bmatrix} 3 & 6 \\ 9 & 12 \end{bmatrix}$$

In [27]:
k = 3
A = np.array([[1,2], [3,4]])
k * A

array([[ 3,  6],
       [ 9, 12]])

In [28]:
A * k

array([[ 3,  6],
       [ 9, 12]])

##### **Phép toán 6: Định thức của ma trận (Determinant)**
Quy tắc: Chỉ thực hiện trên ma trận vuông. Kết quả trả về là một hằng số lẻ (số vô hướng). 

Với ma trận $2 \times 2$ dạng $\begin{bmatrix} a & b \\ c & d \end{bmatrix}$, định thức được tính bằng: $ad - bc$.

Ví dụ:$$\det \begin{bmatrix} 2 & 3 \\ 1 & 5 \end{bmatrix} = (2 \cdot 5) - (3 \cdot 1) = 10 - 3 = 7$$

Syntax:
```bash
np.linalg.det(A)
```

In [29]:
A = np.array([[2,3], [1,5]])
np.linalg.det(A)

7.000000000000001

In [30]:
B = np.array([[2,3,1], [1,5,2], [1,2,1]])
B

array([[2, 3, 1],
       [1, 5, 2],
       [1, 2, 1]])

In [31]:
np.linalg.det(B)

2.0

##### **Phép toán 7: Vết của ma trận (Trace)**
Quy tắc: Chỉ áp dụng trên ma trận vuông. Kết quả thu được bằng cách cộng tất cả các phần tử nằm trên đường chéo chính lại với nhau (các phần tử có chỉ số dòng bằng chỉ số cột $a_{ii}$).

Ví dụ:$$\text{Tr} \begin{bmatrix} \mathbf{5} & 1 & 2 \\ 0 & \mathbf{3} & -1 \\ 6 & 4 & \mathbf{2} \end{bmatrix} = 5 + 3 + 2 = 10$$

In [32]:
A = np.array([[5,1,2], [0,3,-1], [6,4,2]])
np.trace(A)

10

##### **Phép toán 8: Ma trận nghịch đảo (Inverse Matrix)**
Quy tắc: Chỉ áp dụng cho ma trận vuông và định thức của ma trận phải khác 0 ($\det(\mathbf{A}) \neq 0$). 

Ký hiệu: $\mathbf{A}^{-1}$, thỏa mãn điều kiện nhân với ma trận gốc tạo ra ma trận đơn vị: $\mathbf{A}\mathbf{A}^{-1} = \mathbf{A}^{-1}\mathbf{A} = \mathbf{I}$.

Ví dụ: Cho $\mathbf{A} = \begin{bmatrix} 4 & 7 \\ 2 & 6 \end{bmatrix}$. Trực quan công thức nghịch đảo ma trận $2 \times 2$:

$$\mathbf{A}^{-1} = \frac{1}{4\cdot6 - 7\cdot2} \begin{bmatrix} 6 & -7 \\ -2 & 4 \end{bmatrix} = \frac{1}{10} \begin{bmatrix} 6 & -7 \\ -2 & 4 \end{bmatrix} = \begin{bmatrix} 0.6 & -0.7 \\ -0.2 & 0.4 \end{bmatrix}$$

In [33]:
A = np.array([[4,7], [2,6]])
A

array([[4, 7],
       [2, 6]])

In [35]:
np.linalg.det(A)

10.000000000000002

In [34]:
np.linalg.inv(A)

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

##### **Phép toán 9: Ma trận chuyển vị (Transpose)**
Quy tắc: Biến đổi toàn bộ các dòng thành các cột và các cột thành các dòng ($b_{ij} = a_{ji}$). 

Ký hiệu: $\mathbf{A}^{\top}$ hoặc $\mathbf{A}^{\intercal}$.

Ví dụ:
$$\mathbf{A} = \begin{bmatrix} 1 & 2 & 3 \\ 3 & 2 & 1 \end{bmatrix} \implies \mathbf{A}^{\top} = \begin{bmatrix} 1 & 3 \\ 2 & 2 \\ 3 & 1 \end{bmatrix} \text{}$$

In [36]:
A = np.array([[1,2,3], [3,2,1]])
A

array([[1, 2, 3],
       [3, 2, 1]])

In [37]:
A.T

array([[1, 3],
       [2, 2],
       [3, 1]])

## **2. Kỹ thuật tính toán**

#### **2.1. Broadcasting**
Theo quy tắc, không thể cộng một vector và một ma trận vì chúng khác kích thước. Tuy nhiên, trong thực tế, thường xuyên cần thực hiện hành động đó.

Ví dụ: Có một ma trận lưu điểm thi của 40 học sinh (mỗi học sinh có 3 cột điểm Toán, Lý, Hóa). Phát hiện đề Hóa bị sai và muốn cộng thêm 1 điểm vào cột Hóa cho tất cả học sinh.
- Thay vì phải dùng vòng lặp for chạy qua 40 dòng rất chậm chạp, NumPy cung cấp một cơ chế tự động hóa gọi là Broadcasting.
- Broadcasting là cơ chế tự động "kéo dãn" mảng nhỏ hơn để nó có kích thước khớp với mảng lớn hơn, từ đó thực hiện được các phép toán element-wise mà không cần copy thêm dữ liệu vào RAM.

Quy tắc Broadcasting:
- Trong đại số tuyến tính, để cộng 1 điểm Hóa cho 40 học sinh, bắt buộc phải tạo ra một ma trận $\mathbf{B}$ có đúng kích thước $40 \times 3$, trong đó cột 1, 2 chứa toàn số 0 và cột 3 chứa toàn số 1, sau đó tính $\mathbf{A} + \mathbf{B}$.
- Nhưng với cơ chế Broadcasting trong lập trình, chỉ cần tạo một vector 1D mô tả điểm cộng cho 3 môn: [0, 0, 1] (Toán +0, Lý +0, Hóa +1).
- Khi lấy ma trận (40, 3) cộng với vector (3,), máy tính sẽ tự động áp dụng quy tắc Broadcasting: 
    - Máy thấy chiều cuối cùng (số cột) trùng khớp nhau là $3$.
    - Máy tự động "kéo dãn" vector [0, 0, 1] lặp lại 40 lần theo chiều dọc để cộng vào từng học sinh.

In [39]:
A = np.zeros((40,3))
B = np.array([0, 0, 1])

A + B

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

#### **2.2. Giải hệ phương trình tuyến tính**

Cho hệ phương trình tuyến tính 2 ẩn:
    $$\begin{cases} 2x + y = 5 \\ x - y = 1 \end{cases}$$

Hai phương pháp giải hệ phương trình:
- Phương pháp thế (Substitution): 
    - Từ phương trình (2), rút ra $x = 1 + y$. 
    - Thế vào phương trình (1): $2(1 + y) + y = 5 \implies 2 + 3y = 5 \implies y = 1$. 
    - Từ đó tính được $x = 2$.
- Phương pháp cộng đại số (Elimination): 
    - Cộng vế theo vế của hai phương trình để triệt tiêu $y$: $(2x + x) + (y - y) = 5 + 1 \implies 3x = 6 \implies x = 2$. 
    - Thế ngược lại tìm được $y = 1$.

**Programming**:

Để máy tính có thể hiểu được, toàn bộ hệ phương trình trên được chuyển đổi thành một phương trình ma trận duy nhất ở dạng:
    $$\mathbf{A}\mathbf{x} = \mathbf{b}$$
    
Trong đó:
- $\mathbf{A} = \begin{bmatrix} 2 & 1 \\ 1 & -1 \end{bmatrix}$ là Ma trận hệ số (chứa các con số đứng trước ẩn).
- $\mathbf{x} = \begin{bmatrix} x \\ y \end{bmatrix}$ là vector ẩn số cần tìm.
- $\mathbf{b} = \begin{bmatrix} 5 \\ 1 \end{bmatrix}$ là vector kết quả (vế phải).

Về mặt lý thuyết toán học, nghiệm của hệ phương trình này được tìm bằng cách "chia" ma trận $\mathbf{A}$ sang vế phải, hay chính xác là nhân với Ma trận nghịch đảo $\mathbf{A}^{-1}$:
    $$\mathbf{x} = \mathbf{A}^{-1}\mathbf{b}$$

Vậy, chỉ cần tính $\mathbf{A}^{-1}$ rồi nhân với $\mathbf{b}$? 

=> Numpy không làm vậy vì:
- Sai số dấu phẩy động (Floating-Point Errors): Máy tính không lưu được các số thực vô hạn. Khi tính toán ma trận nghịch đảo, nó phải thực hiện hàng triệu phép chia. Các sai số làm tròn nhỏ (ví dụ: $0.33333333$) sẽ tích tụ lại. Với các ma trận lớn, sai số này lớn đến mức có thể biến một nghiệm đúng thành một nghiệm hoàn toàn vô nghĩa.
- Tốn tài nguyên phần cứng: Độ phức tạp thuật toán để tìm ma trận nghịch đảo là $\mathcal{O}(n^3)$. Nếu hệ có 10.000 ẩn, máy tính sẽ phải thực hiện khoảng $10.000^3 = 1.000$ tỷ phép tính.

Giải pháp thực tế: **Thuật toán Phân rã Ma trận (Matrix Decomposition)**
- Biến đổi ma trận phức tạp $\mathbf{A}$ thành tích của hai ma trận tam giác (một ma trận chỉ chứa số ở nửa trên, một ma trận chỉ chứa số ở nửa dưới).

In [41]:
A = np.array([[2.0, 1.0], 
              [1.0, -1.0]])
b = np.array([5.0, 1.0])

x = np.linalg.solve(A, b)
x

array([2., 1.])

In [42]:
print(f"x = {x[0]:.2f}")
print(f"y = {x[1]:.2f}")

x = 2.00
y = 1.00
